# Generated by Django 5.2.4 on 2025-08-02 15:52

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('store_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='hire date')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='position')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='salary')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='username')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='store_management.department', verbose_name='department')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='manager')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='store_management.store', verbose_name='store')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'db_table': 'human_resources_employee',
                'ordering': ['last_name', 'first_name'],
                'permissions': [('view_store_dashboard', 'Can view store management dashboard'), ('manage_store_settings', 'Can modify store configuration and settings'), ('manage_departments', 'Can create/edit/delete store departments'), ('access_inventory', 'Can access inventory management system'), ('view_inventory', 'Can view inventory items and stock levels'), ('edit_inventory', 'Can modify inventory items and quantities'), ('manage_inventory_categories', 'Can organize inventory categories'), ('perform_inventory_audit', 'Can conduct physical inventory counts'), ('process_sales', 'Can process in-store sales transactions'), ('void_sales', 'Can void/completely cancel sales transactions'), ('manage_sales_promotions', 'Can configure sales promotions/discounts'), ('view_sales_reports', 'Can access sales performance reports'), ('create_purchase_orders', 'Can generate new procurement orders'), ('approve_purchase_orders', 'Can authorize procurement requests'), ('manage_suppliers', 'Can maintain supplier/vendor records'), ('receive_stock', 'Can process received shipments'), ('view_employee_directory', 'Can access employee contact information'), ('manage_employee_records', 'Can maintain HR records (excluding sensitive data)'), ('access_hr_reports', 'Can view HR analytics and reports'), ('manage_recruitment', 'Can handle hiring processes'), ('manage_online_listings', 'Can maintain e-commerce product listings'), ('process_online_orders', 'Can fulfill e-commerce purchases'), ('handle_customer_portals', 'Can manage customer account portals'), ('view_web_analytics', 'Can access e-commerce traffic/revenue reports'), ('generate_financial_reports', 'Can create financial statements'), ('export_data_reports', 'Can export datasets for external analysis'), ('access_executive_dashboards', 'Can view strategic business dashboards'), ('schedule_automated_reports', 'Can configure report automation'), ('override_inventory_checks', 'Can bypass inventory validation rules'), ('access_audit_logs', 'Can view system audit trails'), ('manage_api_integrations', 'Can configure system integrations')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
