# Generated by Django 5.2.4 on 2025-08-31 18:58

import django.contrib.auth.models
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('on_leave', 'On Leave')], default='present', max_length=20)),
                ('notes', models.TextField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='hire date')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='position')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='salary')),
                ('qualifications', models.TextField(blank=True, help_text="List the employee's qualifications, certifications, and educational background", null=True, verbose_name='qualifications')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='username')),
                ('profile_image', models.ImageField(blank=True, help_text='Upload a profile picture for this employee', null=True, upload_to='employee_profiles/', verbose_name='profile image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'db_table': 'human_resources_employee',
                'ordering': ['last_name', 'first_name'],
                'permissions': [('view_store_dashboard', 'Can view store management dashboard'), ('manage_store_settings', 'Can modify store configuration and settings'), ('manage_departments', 'Can create/edit/delete store departments'), ('access_inventory', 'Can access inventory management system'), ('view_inventory', 'Can view inventory items and stock levels'), ('edit_inventory', 'Can modify inventory items and quantities'), ('manage_inventory_categories', 'Can organize inventory categories'), ('perform_inventory_audit', 'Can conduct physical inventory counts'), ('process_sales', 'Can process in-store sales transactions'), ('void_sales', 'Can void/completely cancel sales transactions'), ('manage_sales_promotions', 'Can configure sales promotions/discounts'), ('view_sales_reports', 'Can access sales performance reports'), ('create_purchase_orders', 'Can generate new procurement orders'), ('approve_purchase_orders', 'Can authorize procurement requests'), ('manage_suppliers', 'Can maintain supplier/vendor records'), ('receive_stock', 'Can process received shipments'), ('view_employee_directory', 'Can access employee contact information'), ('manage_employee_records', 'Can maintain HR records (excluding sensitive data)'), ('access_hr_reports', 'Can view HR analytics and reports'), ('manage_recruitment', 'Can handle hiring processes'), ('manage_online_listings', 'Can maintain e-commerce product listings'), ('process_online_orders', 'Can fulfill e-commerce purchases'), ('handle_customer_portals', 'Can manage customer account portals'), ('view_web_analytics', 'Can access e-commerce traffic/revenue reports'), ('generate_financial_reports', 'Can create financial statements'), ('export_data_reports', 'Can export datasets for external analysis'), ('access_executive_dashboards', 'Can view strategic business dashboards'), ('schedule_automated_reports', 'Can configure report automation'), ('override_inventory_checks', 'Can bypass inventory validation rules'), ('access_audit_logs', 'Can view system audit trails'), ('manage_api_integrations', 'Can configure system integrations')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Payroll Records',
                'ordering': ['-pay_period_end', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('training_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_completed', models.DateField()),
                ('certification_status', models.CharField(blank=True, max_length=100, null=True)),
                ('provider', models.CharField(blank=True, max_length=255, null=True, verbose_name='Training Provider')),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Duration of the training in hours', max_digits=5, null=True, verbose_name='Duration (Hours)')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost of the training in SZL', max_digits=10, null=True, verbose_name='Cost')),
                ('certificate_number', models.CharField(blank=True, help_text='Certificate or reference number', max_length=100, null=True, verbose_name='Certificate Number')),
                ('expiry_date', models.DateField(blank=True, help_text='Date when certification expires', null=True, verbose_name='Expiry Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Training Record',
                'verbose_name_plural': 'Training Records',
                'ordering': ['-date_completed'],
            },
        ),
    ]
