# Generated by Django 5.2.4 on 2025-10-20 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_initial'),
        ('store_management', '0003_store_store_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='shift name')),
                ('shift_type', models.CharField(choices=[('morning', 'Morning Shift'), ('afternoon', 'Afternoon Shift'), ('evening', 'Evening Shift'), ('night', 'Night Shift'), ('weekend', 'Weekend Shift'), ('holiday', 'Holiday Shift'), ('overtime', 'Overtime Shift'), ('flexible', 'Flexible Hours'), ('other', 'Other')], default='morning', max_length=20, verbose_name='shift type')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Duration in hours (auto-calculated)', max_digits=4, null=True, verbose_name='duration hours')),
                ('description', models.TextField(blank=True, help_text='Optional description of the shift', null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_departments', models.ManyToManyField(blank=True, help_text='Departments where this shift can be used (leave empty for all departments)', related_name='allowed_shifts', to='store_management.department', verbose_name='allowed departments')),
                ('allowed_stores', models.ManyToManyField(blank=True, help_text='Stores where this shift can be used (leave empty for all stores)', related_name='allowed_shifts', to='store_management.store', verbose_name='allowed stores')),
            ],
            options={
                'verbose_name': 'Shift Template',
                'verbose_name_plural': 'Shift Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='scheduled date')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20, verbose_name='status')),
                ('custom_start_time', models.TimeField(blank=True, help_text="Override the shift's start time", null=True, verbose_name='custom start time')),
                ('custom_end_time', models.TimeField(blank=True, help_text="Override the shift's end time", null=True, verbose_name='custom end time')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this schedule', null=True, verbose_name='notes')),
                ('actual_start_time', models.TimeField(blank=True, help_text='Actual time employee started work', null=True, verbose_name='actual start time')),
                ('actual_end_time', models.TimeField(blank=True, help_text='Actual time employee ended work', null=True, verbose_name='actual end time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Supervisor who assigned this schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_schedules', to='human_resources.employee', verbose_name='assigned by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='human_resources.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='human_resources.shift')),
            ],
            options={
                'verbose_name': 'Employee Schedule',
                'verbose_name_plural': 'Employee Schedules',
                'ordering': ['-date', 'employee'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_date_schedule')],
            },
        ),
    ]
