# Generated by Django 5.2.4 on 2025-09-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('on_leave', 'On Leave'), ('sick_leave', 'Sick Leave'), ('vacational_leave', 'Vacational Leave'), ('maternity_leave', 'Maternity Leave'), ('study_leave', 'Study Leave'), ('compassionate_leave', 'Compassionate Leave')], default='present', max_length=20),
        ),
    ]
