# Generated by Django 5.2.4 on 2025-10-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, help_text='Final net pay amount', max_digits=10),
        ),
    ]
