# Generated by Django 5.2.4 on 2025-10-20 20:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_shift_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='approval_levels',
            field=models.PositiveIntegerField(default=1, help_text='Number of approval levels required', verbose_name='approval levels'),
        ),
        migrations.AddField(
            model_name='shift',
            name='approval_required',
            field=models.BooleanField(default=False, help_text='Whether this shift requires approval before assignment', verbose_name='approval required'),
        ),
        migrations.AddField(
            model_name='shift',
            name='break_times',
            field=models.JSONField(blank=True, help_text="Break schedule in JSON format: [{'start': '10:00', 'end': '10:15', 'type': 'lunch'}, ...]", null=True, verbose_name='break times'),
        ),
        migrations.AddField(
            model_name='shift',
            name='overtime_rules',
            field=models.TextField(blank=True, help_text='Rules for overtime calculation and approval', null=True, verbose_name='overtime rules'),
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='cost center code')),
                ('name', models.CharField(max_length=100, verbose_name='cost center name')),
                ('description', models.TextField(blank=True, help_text='Description of this cost center', null=True, verbose_name='description')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Annual budget for this cost center', max_digits=12, null=True, verbose_name='annual budget')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, help_text='Manager responsible for this cost center', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cost_centers', to='human_resources.employee', verbose_name='cost center manager')),
            ],
            options={
                'verbose_name': 'Cost Center',
                'verbose_name_plural': 'Cost Centers',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='cost_center',
            field=models.ForeignKey(blank=True, help_text='Cost center this shift belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='human_resources.costcenter', verbose_name='cost center'),
        ),
    ]
