# Generated by Django 5.2.4 on 2025-10-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_shift_approval_levels_shift_approval_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
    ]
