# Generated by Django 5.2.4 on 2025-09-02 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='marketing_opt_in',
            field=models.BooleanField(default=False, verbose_name='Marketing Communications'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('si', 'siSwati')], default='en', max_length=10, verbose_name='Preferred Language'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='push_notifications',
            field=models.BooleanField(default=True, verbose_name='Push Notifications'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='sms_notifications',
            field=models.BooleanField(default=False, verbose_name='SMS Notifications'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Guest Email'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='guest_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='guest_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='online_orders', to='e_commerce.customeraccount'),
        ),
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('digital_wallet', 'Digital Wallet')], max_length=20)),
                ('card_last_four', models.CharField(blank=True, max_length=4, null=True, verbose_name='Last 4 Digits')),
                ('card_brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='Card Brand')),
                ('expiry_month', models.PositiveIntegerField(blank=True, null=True)),
                ('expiry_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_payment_methods', to='e_commerce.customeraccount')),
            ],
            options={
                'verbose_name': 'Saved Payment Method',
                'verbose_name_plural': 'Saved Payment Methods',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('customer', 'is_default'), name='unique_default_payment')],
            },
        ),
    ]
