# Generated by Django 5.2.4 on 2025-10-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_onlineorder_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='gift_wrapping',
            field=models.BooleanField(default=False, help_text='Whether gift wrapping is requested'),
        ),
    ]
