# Generated by Django 5.2.4 on 2025-10-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_onlineorder_payment_date_onlineorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='billing_address',
            field=models.TextField(blank=True, null=True, verbose_name='Billing Address'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='billing_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='billing_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='billing_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='gift_message',
            field=models.TextField(blank=True, null=True, verbose_name='Gift Message'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='gift_wrapping',
            field=models.BooleanField(default=False, verbose_name='Gift Wrapping'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='guest_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='guest_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='guest_marketing_opt_in',
            field=models.BooleanField(default=False, verbose_name='Marketing Communications'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='guest_preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('si', 'siSwati')], default='en', max_length=10, verbose_name='Preferred Language'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='guest_push_notifications',
            field=models.BooleanField(default=True, verbose_name='Push Notifications'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='guest_sms_notifications',
            field=models.BooleanField(default=False, verbose_name='SMS Notifications'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='loyalty_program_signup',
            field=models.BooleanField(default=False, verbose_name='Join Loyalty Program'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='order_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Order Notes/Special Instructions'),
        ),
    ]
