# Generated by Django 5.2.4 on 2025-10-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_onlineorder_gift_wrapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='payment_method',
            field=models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('payfast', 'PayFast'), ('mygate', 'MyGate'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('digital_wallet', 'Digital Wallet')], max_length=20),
        ),
    ]
