# Generated by Django 5.2.4 on 2025-10-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_onlineorder_billing_address_onlineorder_billing_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='gift_wrapping',
            field=models.BooleanField(default=False, verbose_name='Gift Wrapping'),
        ),
    ]
