# Generated by Django 5.2.4 on 2025-12-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0005_alter_onlineorder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
