# Generated by Django 5.2.4 on 2025-10-09 20:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('opening_date', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Website URL')),
                ('fax_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax Number')),
                ('secondary_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Secondary Contact Person')),
                ('store_type', models.CharField(choices=[('retail', 'Retail Store'), ('flagship', 'Flagship Store'), ('outlet', 'Outlet Store'), ('warehouse', 'Warehouse'), ('franchise', 'Franchise'), ('pop_up', 'Pop-up Store')], default='retail', max_length=20, verbose_name='Store Type')),
                ('store_size', models.DecimalField(blank=True, decimal_places=2, help_text='Store size in square meters', max_digits=10, null=True, verbose_name='Store Size (sq m)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Store Description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_renovation', 'Under Renovation'), ('closed', 'Closed')], default='active', max_length=20, verbose_name='Store Status')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Opening Time')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Closing Time')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stores', to='human_resources.employee', verbose_name='Store Manager')),
            ],
            options={
                'db_table': 'store_management_store',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='store_management.store')),
            ],
            options={
                'db_table': 'store_management_department',
                'ordering': ['department_name'],
                'constraints': [models.UniqueConstraint(fields=('store', 'department_name'), name='unique_department_per_store')],
            },
        ),
    ]
