# Generated by Django 5.2.4 on 2025-09-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='store',
            name='manager',
        ),
    ]
