# Generated by Django 5.2.4 on 2025-08-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0002_rename_department_id_department_id_and_more'),
    ]

    operations = [
    ]
