# Generated by Django 5.2.4 on 2025-10-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0002_rename_store_name_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_number',
            field=models.CharField(blank=True, help_text='Unique store identifier, auto-generated if left blank', max_length=20, null=True, unique=True, verbose_name='Store Number'),
        ),
    ]
