# Generated by Django 5.2.4 on 2025-09-10 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_initial'),
        ('store_management', '0002_remove_department_manager_remove_store_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stores', to='human_resources.employee', verbose_name='Store Manager'),
        ),
    ]
