# Generated by Django 5.2.4 on 2025-08-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0003_auto_20250802_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department_name']},
        ),
    ]
