# Generated by Django 5.2.4 on 2025-08-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0004_alter_department_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.AutoField(db_column='store_id', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store_id',
            new_name='id',
        ),
    ]
