# Generated by Django 5.2.4 on 2025-09-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='aesthetic_description',
            field=models.TextField(blank=True, help_text='Visual style, color preferences, design principles', null=True, verbose_name='Aesthetic Guidelines'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_assets',
            field=models.FileField(blank=True, help_text='Upload brand guidelines, fonts, or other assets', null=True, upload_to='brand_assets/', verbose_name='Brand Assets (ZIP)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_story',
            field=models.TextField(blank=True, help_text='The narrative and values that define the brand', null=True, verbose_name='Brand Story'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_voice',
            field=models.TextField(blank=True, help_text="Describe the brand's personality, tone, and communication style", null=True, verbose_name='Brand Voice & Personality'),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logos/', verbose_name='Brand Logo'),
        ),
        migrations.AddField(
            model_name='brand',
            name='primary_color',
            field=models.CharField(blank=True, help_text='e.g., #FF5733', max_length=7, null=True, verbose_name='Primary Color (Hex)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='secondary_color',
            field=models.CharField(blank=True, help_text='e.g., #33FF57', max_length=7, null=True, verbose_name='Secondary Color (Hex)'),
        ),
    ]
