# Generated by Django 5.2.4 on 2025-10-13 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_initial'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='performed_by',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resources.employee'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inventory_records', to='human_resources.employee'),
        ),
    ]
