# Generated by Django 5.2.4 on 2025-10-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_stockmovement_performed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_online',
            field=models.BooleanField(default=False, verbose_name='Show Online'),
        ),
    ]
