# Generated by Django 5.2.4 on 2025-10-27 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_shift_approval_levels_shift_approval_required_and_more'),
        ('inventory', '0004_alter_stockmovement_reason_inventoryalert_and_more'),
        ('procurement', '0004_supplier_auto_fulfill_orders_and_more'),
        ('store_management', '0003_store_store_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpirationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Configuration name (e.g., 'Default', 'Perishable Goods')", max_length=100, unique=True)),
                ('alert_thresholds', models.JSONField(default=dict, help_text="Alert thresholds in days (e.g., {'critical': 7, 'warning': 14, 'info': 30})")),
                ('auto_prevent_sales', models.BooleanField(default=True, help_text='Automatically prevent sales of expired items')),
                ('notification_recipients', models.JSONField(default=list, help_text="List of recipient groups (e.g., ['Management', 'Inventory', 'Procurement'])")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expiration Configuration',
                'verbose_name_plural': 'Expiration Configurations',
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Configuration name (e.g., 'Default', 'High-Value Items')", max_length=100, unique=True)),
                ('auto_replenishment_enabled', models.BooleanField(default=True, help_text='Enable automatic replenishment processing')),
                ('batch_processing_enabled', models.BooleanField(default=True, help_text='Enable bulk procurement batching')),
                ('auto_approval_enabled', models.BooleanField(default=False, help_text='Enable automatic approval of purchase orders')),
                ('max_auto_approval_amount', models.DecimalField(decimal_places=2, default=1000.0, help_text='Maximum PO amount for auto-approval', max_digits=12)),
                ('safety_stock_multiplier', models.DecimalField(decimal_places=1, default=1.5, help_text='Multiplier for safety stock calculation', max_digits=3)),
                ('lead_time_buffer_days', models.IntegerField(default=2, help_text='Extra days to add to lead time for safety')),
                ('min_order_frequency_days', models.IntegerField(default=7, help_text='Minimum days between automatic orders for same product')),
                ('notification_enabled', models.BooleanField(default=True, help_text='Enable replenishment notifications')),
                ('notification_recipients', models.JSONField(default=list, help_text='List of recipient groups for notifications')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Replenishment Configuration',
                'verbose_name_plural': 'Replenishment Configurations',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='demand_variability',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Coefficient of variation for demand (0-1)', max_digits=5, verbose_name='Demand Variability'),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_stock',
            field=models.IntegerField(default=0, help_text='Minimum stock to maintain as buffer', verbose_name='Safety Stock Level'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_velocity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average units sold per day', max_digits=8, verbose_name='Sales Velocity'),
        ),
        migrations.CreateModel(
            name='ReplenishmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(help_text='Unique batch identifier', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_items', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resources.employee')),
                ('purchase_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishment_batch', to='procurement.purchaseorder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_batches', to='store_management.store')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_batches', to='procurement.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_items', to='inventory.replenishmentbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'unique_together': {('batch', 'product')},
            },
        ),
    ]
