# Generated by Django 5.2.4 on 2025-10-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_expirationconfig_replenishmentconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='criticality',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='Importance level for inventory management', max_length=10, verbose_name='Criticality'),
        ),
    ]
