# Generated by Django 5.2.4 on 2025-10-27 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_shift_approval_levels_shift_approval_required_and_more'),
        ('inventory', '0006_product_criticality'),
        ('store_management', '0003_store_store_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(blank=True, choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('RETURN', 'Return'), ('DAMAGE', 'Damage'), ('THEFT', 'Theft'), ('ADJUSTMENT', 'Adjustment'), ('AUTO_REORDER', 'Auto Reorder'), ('TRANSFER', 'Transfer')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(help_text='Unique transfer identifier', max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to='human_resources.employee')),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='store_management.store')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfers', to='inventory.product')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to='human_resources.employee')),
                ('to_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='store_management.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('transfer_id',)},
            },
        ),
    ]
