# Generated by Django 5.2.4 on 2025-10-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='industry',
            field=models.CharField(blank=True, help_text='Industry or sector the supplier operates in', max_length=100, null=True, verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the supplier', null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(blank=True, help_text="Supplier's tax identification number", max_length=50, null=True, verbose_name='Tax ID'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, help_text="Supplier's website URL", null=True, verbose_name='Website'),
        ),
    ]
