# Generated by Django 5.2.4 on 2025-09-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='api_endpoint',
            field=models.URLField(blank=True, help_text='Third-party API endpoint for integration', null=True, verbose_name='API Endpoint'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='compliance_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Compliance Score (%)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='on_time_delivery_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='On-Time Delivery Rate (%)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='quality_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Quality Rating (1-5)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tenant_id',
            field=models.CharField(blank=True, help_text='For multi-tenant architecture', max_length=50, null=True, verbose_name='Tenant ID'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
