# Generated by Django 5.2.4 on 2025-08-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
