# Generated by Django 5.2.4 on 2025-08-26 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_employee_profile_image_alter_attendance_employee_and_more'),
        ('procurement', '0002_supplier_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resources.employee'),
        ),
    ]
