# Generated by Django 5.2.4 on 2025-10-27 07:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0005_alter_onlineorder_payment_method'),
        ('inventory', '0003_remove_stockmovement_performed_by_and_more'),
        ('procurement', '0003_alter_purchaseorder_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='auto_fulfill_orders',
            field=models.BooleanField(default=False, help_text='Automatically place orders on platform when sales occur', verbose_name='Auto Fulfill Orders'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='auto_sync_inventory',
            field=models.BooleanField(default=False, help_text='Automatically sync inventory levels from platform', verbose_name='Auto Sync Inventory'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_dropshipping_supplier',
            field=models.BooleanField(default=False, help_text='Check if this supplier supports dropshipping', verbose_name='Dropshipping Supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='platform_supplier_id',
            field=models.CharField(blank=True, help_text='Supplier ID on the dropshipping platform', max_length=100, null=True, verbose_name='Platform Supplier ID'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='platform_type',
            field=models.CharField(blank=True, choices=[('dsers', 'DSers'), ('aliexpress', 'AliExpress'), ('oberlo', 'Oberlo'), ('other', 'Other')], help_text='e.g., DSers, AliExpress, Oberlo', max_length=50, null=True, verbose_name='Platform Type'),
        ),
        migrations.CreateModel(
            name='DSersOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsers_order_id', models.CharField(max_length=100, unique=True, verbose_name='DSers Order ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Order Status')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tracking Number')),
                ('shipping_carrier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping Carrier')),
                ('dsers_data', models.JSONField(help_text='Raw JSON data from DSers API', verbose_name='DSers Order Data')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsers_orders', to='e_commerce.onlineorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsers_orders', to='procurement.supplier')),
            ],
            options={
                'verbose_name': 'DSers Order',
                'verbose_name_plural': 'DSers Orders',
            },
        ),
        migrations.CreateModel(
            name='DSersProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsers_product_id', models.CharField(max_length=100, unique=True, verbose_name='DSers Product ID')),
                ('dsers_data', models.JSONField(help_text='Raw JSON data from DSers API', verbose_name='DSers Product Data')),
                ('last_synced', models.DateTimeField(auto_now=True, verbose_name='Last Synced')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is active for dropshipping', verbose_name='Active')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dsers_product', to='inventory.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsers_products', to='procurement.supplier')),
            ],
            options={
                'verbose_name': 'DSers Product',
                'verbose_name_plural': 'DSers Products',
            },
        ),
    ]
