# Generated by Django 5.2.4 on 2025-10-27 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('procurement', '0004_supplier_auto_fulfill_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='replenishment_status',
            field=models.CharField(choices=[('manual', 'Manual Order'), ('auto_triggered', 'Auto Triggered'), ('predictive', 'Predictive Reorder'), ('bulk_batch', 'Bulk Batch Order')], default='manual', help_text='How this order was created', max_length=20, verbose_name='Replenishment Status'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='auto_approval_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum order value for automatic approval', max_digits=12, null=True, verbose_name='Auto Approval Threshold'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='preferred_supplier',
            field=models.BooleanField(default=False, help_text='This is the preferred supplier for this product', verbose_name='Preferred Supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('auto_approved', 'Auto Approved'), ('shipped', 'Shipped'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
