# Generated by Django 5.2.4 on 2025-10-27 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_purchaseorder_approved_at_purchaseorder_approved_by_and_more'),
        ('store_management', '0003_store_store_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse receiving the transfer (for warehouse transfers only)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='store_management.store', verbose_name='Destination Warehouse'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='order_type',
            field=models.CharField(choices=[('supplier_order', 'Order from Supplier'), ('warehouse_transfer', 'Transfer from Warehouse')], default='supplier_order', help_text='Type of order: from supplier or warehouse transfer', max_length=20, verbose_name='Order Type'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store_management.store', verbose_name='Ordering Store'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.supplier'),
        ),
    ]
