# Generated by Django 5.2.4 on 2025-09-03 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_customeraccount_marketing_opt_in_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_account',
            field=models.OneToOneField(blank=True, help_text='Link to the customer account from the customer portal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_customer', to='e_commerce.customeraccount'),
        ),
    ]
