# Generated by Django 5.2.4 on 2025-10-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='marketing_opt_in',
            field=models.BooleanField(default=False, verbose_name='Marketing Opt-in'),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Customer Notes'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('mail', 'Mail')], default='email', max_length=20, verbose_name='Preferred Contact Method'),
        ),
        migrations.AddField(
            model_name='customer',
            name='social_media',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Social Media Handle'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_address',
            field=models.TextField(blank=True, null=True, verbose_name='Delivery Address'),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Invoice Number'),
        ),
        migrations.AddField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Sale Notes'),
        ),
        migrations.AddField(
            model_name='sale',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='completed', max_length=20, verbose_name='Order Status'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sales_channel',
            field=models.CharField(choices=[('in_store', 'In-Store'), ('online', 'Online'), ('phone', 'Phone'), ('marketplace', 'Marketplace')], default='in_store', max_length=20, verbose_name='Sales Channel'),
        ),
    ]
