# Generated by Django 5.2.4 on 2025-10-13 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sales', '0002_customer_date_of_birth_customer_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='accounts.employee'),
        ),
    ]
