# Generated by Django 5.2.4 on 2025-08-26 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_employee_profile_image_alter_attendance_employee_and_more'),
        ('sales', '0002_salestransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='human_resources.employee'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='human_resources.employee'),
        ),
    ]
