# Generated by Django 5.2.4 on 2025-10-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_return_employee_alter_sale_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='data_processing_consent',
            field=models.BooleanField(default=False, verbose_name='Data Processing Consent'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Email Notifications'),
        ),
        migrations.AddField(
            model_name='customer',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency Contact Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AddField(
            model_name='customer',
            name='language_preference',
            field=models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('french', 'French'), ('german', 'German'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('other', 'Other')], default='english', max_length=20, verbose_name='Preferred Language'),
        ),
        migrations.AddField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True, verbose_name='Marital Status'),
        ),
        migrations.AddField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='number_of_dependents',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of Dependents'),
        ),
        migrations.AddField(
            model_name='customer',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Occupation'),
        ),
        migrations.AddField(
            model_name='customer',
            name='push_notifications',
            field=models.BooleanField(default=False, verbose_name='Push Notifications'),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('word_of_mouth', 'Word of Mouth'), ('social_media', 'Social Media'), ('advertisement', 'Advertisement'), ('website', 'Website'), ('friend_family', 'Friend/Family'), ('search_engine', 'Search Engine'), ('other', 'Other')], max_length=20, null=True, verbose_name='How did you hear about us?'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sms_notifications',
            field=models.BooleanField(default=False, verbose_name='SMS Notifications'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State/Province'),
        ),
    ]
